### ISSUE TITLE
No way to create a new gallery after adding a gallery component

### ISSUE THREAD

**Issue by michaelbeil** [AesopInteractive/lasso#28]
1. Create gallery
2. Add gallery
3. Save
4. Refresh
5. Repeat
6. Galleries go crazy

**Comment by bearded-avenger** [comment]
i think this was fixed a while back yeah?

**Comment by michaelbeil** [comment]
This is still an issue it would appear as I have added multiple galleries and they all become the same as the most recently added gallery. 

Do you have the same results @bearded-avenger?
